package com.mingsun.cs2800;

/**
 * @author Ming Sun <email zaac003@live.rhul.ac.uk>
 * @since 2014-10-12
 */
public class MyException extends Exception {
	/**
	 * This is exception serial version UID generated by eclipse.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constructor which is empty.
	 */
	public MyException() {
	}

	/**
	 * Constructor which takes the exception information.
	 * 
	 * @param message
	 *            Exception message
	 */
	public MyException(final String message) {
		super(message);
	}

}
